name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      build:
        context: .
        dockerfile: .devcontainer/Dockerfile
    steps:
      - uses: actions/checkout@v3
      - run: pip3 install -r requirements.txt
      - run: pytest -q
